### PR TITLE
Add Xray iteration support

### PR DESCRIPTION
**Pull request by csvtuda**
This PR adds iteration support as discussed in #90.

image

When reviewing the changes, please keep in mind that:

- Xray tests without datasets (i.e. not data-driven) are compatible with normal/single result uploads
- Xray tests without datasets (i.e. not data-driven) are compatible with iteration/multi result uploads

   - this facilitates result uploads of retries by treating them as iterations

- Xray tests with datasets (i.e. data-driven) are _incompatible_ with normal/single result uploads

   image

- Xray tests with datasets (i.e. data-driven) are compatible with iteration/multi result uploads

   - parameters do not necessarily need to match, e.g. the upload still works fine for parameters `iteration=...` even if the test case's dataset shape is `name=...`

---

The process is basically as follows:

1. Group all test results by the issue key in their titles
    - this includes individual results, data-driven results _as well as retry results_ (!)
3. If there's just one test result for an issue key: upload as usual
4. If there's more than one test result for an issue key: upload as iterations

Playwright results are actually very easy to handle here. Retry results can be treated like any other (data-driven) results without any additional logic.

---

### Key changes

I tried to touch as little existing code as possible, but I had to do that here and there.

- moved conversion logic to its own file
- added a few conversion tests using Node's native test runner + [tsx](https://www.npmjs.com/package/tsx) for TypeScript file execution (`npm run test`)
- added two example test files for a data-driven test and one with retries
- refactored the Xray types a little bit

### Open topics

- [x] I used prettier for formatting based on the `npm run format` script. I did not use biome formatting. Is this ok?
- [ ] The example test files require `XRAYISSUE` and `TES` issue keys. Since I don't have access to your projects, you will probably need to tell me/add them yourself when trying it out.
- [x] I don't know how the changes affect your flakiness detection. This is probably an area that requires changes. Is the flakiness option still relevant if each retry is its own iteration?
- [ ] I _think_ you can drop the dayjs dependency. As far as I know, Xray simply does not like milliseconds in datetime ISO strings. In my plugin, the following code snippet works fine for both Xray server and Xray cloud when converting date ISO strings to Xray-compatible datetime strings:

    ```ts
    /**
     * Remove milliseconds from ISO time string.
     *
     * @param time - a date time string in ISO format
     * @returns the truncated date time string
     * @example
     *   const time = truncateISOTime("2022-12-01T02:30:44.744Z")
     *   console.log(time); // "2022-12-01T02:30:44Z"
     */
    export function truncateIsoTime(time: string): string {
        return time.split(".")[0] + "Z";
    }
    ```

- [ ] Iteration parameters are simply `iteration=#iteration` for now (the little blue numbers in the screenshot above). I have not implemented any custom parameter mapping (iteration 1 `name=Bob` and so on). I only added this because Xray expects at least one parameter per iteration.

### CODE REVIEW

**Comment by inluxc** [comment]
Can you please use Biome, its a standard in this project.

**Comment by csvtuda** [comment]
Done.

**Comment by NiklasBack** [comment]
Yes, I will run it in our piplines asap

**Comment by NiklasBack** [comment]
I tried it but it doesn’t flag a successful retry as flaky (but the iterations are there)

**Comment by csvtuda** [comment]
> I tried it but it doesn’t flag a successful retry as flaky, it gets flagged as failed (but the iterations are there)

Yeah this is one of the open topics I mentioned above (the third one). I assume you'll want to keep the flakiness flagging?

**Comment by Niklas-Back** [comment]
When one test passes the entire suite should be marked with what's specified in the flaky flag, but the iterations should be marked with pass/ fail

**Comment by csvtuda** [comment]
I adapted the flakiness detection to the iteration changes in b0d2bb3.

- Tests without iterations are never flaky.
- Tests with iterations are considered passing if _at least_ one iteration passes.
  - These are further considered flaky if the flakiness option is defined.
- Tests with iterations are considered failing if _all_ iterations failed or timed out.

**Comment by NiklasBack** [comment]
Perfekt, let me run it in our pipelines again

**Comment by inluxc** [comment]
I love the power of open source. Collab all the way.

**Comment by Niklas-Back** [comment]
I'll have a look on Monday but so far so good 😃

**Review by NiklasBack — APPROVED** [review]
Looks good

**Comment by inluxc** [comment]
Looks good, can you update the Readme with explanations about adding iteration?
Thanks

**Comment by csvtuda** [comment]
I updated the README in 358478d: https://github.com/csvtuda/playwright-xray/tree/main?tab=readme-ov-file#xray-iteration-support

**Review by inluxc — APPROVED** [review]

**Pull request merged**
