### PR TITLE
#83 Add Biome to Project

### PR DESCRIPTION
**Pull request by inluxc**
Add Biome to the project to check possible errors in code.

https://biomejs.dev/

### CODE REVIEW

**Comment by NiklasBack** [comment]
Looks ok, shall I include it in my PR?

**Comment by inluxc** [comment]
Theres is an error in the actions.. 
i need to check it.. 
If you want you can see it also..

**Comment by inluxc** [comment]
@NiklasBack i dont have an env. to test now... 

Can you test this PR.. 
Their is an tyope any need to be fixed.

**Comment by Niklas-Back** [comment]
Ill have a look

**Comment by NiklasBack** [comment]
Let me run it in our environments a couple of times

**Pull request merged**
